[providers.op]
cmd = "op read {uri}"

[providers.tf]
cmd = "terraform -chdir=iac/stages/{stage} output -raw {path}"

[project]
name = "krondor-generic"
users = ["admin", "kamal"]
admin_user = "admin"
admin_email = "alex@getquotient.ai"
tfc_org = "krondor-generic-org"
dns_root_zone = "example.com"

[vaults]
cloud = "cloud-providers"
app = "krondor-generic-production"

[credentials.server]
ip = "tf://server_ip"

[credentials.ssh]
private_key = "secret://tf://ssh_private_key"
public_key = "tf://ssh_public_key"

[credentials.cloud]
docker_hub_token = "secret://op://{vaults.cloud}/DOCKER_HUB_TOKEN/credential"
cloudflare_api_token = "secret://op://{vaults.cloud}/CLOUDFLARE_API_TOKEN/credential"
cloudflare_account_id = "op://{vaults.cloud}/CLOUDFLARE_API_TOKEN/username"
digitalocean_token = "secret://op://{vaults.cloud}/DIGITALOCEAN_TOKEN/credential"
tfc_token = "secret://op://{vaults.cloud}/TFC_TOKEN/credential"

[credentials.app]
google_oauth_client_id = "secret://op://{vaults.app}/GOOGLE_OAUTH/client_id"
google_oauth_client_secret = "secret://op://{vaults.app}/GOOGLE_OAUTH/client_secret"
anthropic_api_key = "secret://op://{vaults.app}/ANTHROPIC_API_KEY/credential"

[services.py]
repo = "amiller68/generic"
domain = "py.{project.dns_root_zone}"
port = 8000

[services.ts-web]
repo = "amiller68/generic"
domain = "ts.{project.dns_root_zone}"
port = 3000

[services.rust]
repo = "amiller68/generic"
domain = "rust.{project.dns_root_zone}"
port = 3000
