service: <%= `confit resolve project.name`.strip %>-rust
deploy_timeout: 180
image: <%= `confit resolve credentials.cloud.docker_hub_username`.strip %>/<%= `confit resolve project.name`.strip %>-rust

servers:
  web:
    - <%= `confit --set stage=production resolve credentials.server.ip`.strip %>

ssh:
  user: kamal

registry:
  username: <%= `confit resolve credentials.cloud.docker_hub_username`.strip %>
  password:
    - DOCKER_HUB_TOKEN

builder:
  dockerfile: web/rust/Dockerfile
  context: web
  arch: amd64
  cache:
    type: registry

proxy:
  ssl: true
  host: <%= `confit resolve services.rust.domain`.strip %>
  app_port: <%= `confit resolve services.rust.port`.strip %>
  healthcheck:
    path: /_status/livez

env:
  secret:
    - GOOGLE_O_AUTH_CLIENT_ID
    - GOOGLE_O_AUTH_CLIENT_SECRET
  clear:
    SQLITE_DATABASE_URL: sqlite:///data/app.db
    LISTEN_ADDRESS: 0.0.0.0:3000
    HOST_NAME: https://<%= `confit resolve services.rust.domain`.strip %>
    LOG_LEVEL: info

volumes:
  - /var/lib/kamal-volumes/<%= `confit resolve project.name`.strip %>-rust/data:/data
