service: <%= `confit resolve project.name`.strip %>-ts-web
deploy_timeout: 180
image: <%= `confit resolve credentials.cloud.docker_hub_username`.strip %>/<%= `confit resolve project.name`.strip %>-ts-web

servers:
  web:
    - <%= `confit --set stage=production resolve credentials.server.ip`.strip %>

ssh:
  user: kamal

registry:
  username: <%= `confit resolve credentials.cloud.docker_hub_username`.strip %>
  password:
    - DOCKER_HUB_TOKEN

builder:
  dockerfile: web/ts/apps/web/Dockerfile
  context: web
  arch: amd64
  cache:
    type: registry

proxy:
  ssl: true
  host: <%= `confit resolve services.ts-web.domain`.strip %>
  app_port: <%= `confit resolve services.ts-web.port`.strip %>
  healthcheck:
    path: /

env:
  clear: {}
